### ISSUE TITLE
Добавить поддержку дополнительных обработок и отчтов

### ISSUE THREAD

**Issue by ivanov660** [Polyplastic/1c-parsing-tech-log#17]
**Требуется** возможность прикреплять дополнительные отчеты и обработки

**Comment by AnatoliyBritko** [comment]
Может имеет смысл еще какие-нидь подсистемы взять из БСП: рассылка отчетов, регл задания, печать и пр.

**Comment by ivanov660** [comment]
1. Нельзя взять БСП и интегрировать. На форуме поддержки уже более 3х лет висит без ответа вопрос о "особенностях" лицензирования бсп в открытых проектах. 
2. Мне бсп не нравится - очень она огромная и неповоротливая.
3. Мне нравится "переосмысление" этого монстра.
4. Дискуссию по вопросу БСП закрываем.

**Comment by ivanov660** [comment]
Необходимый минимум доработок внесен, запрос ушел.
