### ISSUE TITLE
Выложить все в Releases на github

### ISSUE THREAD

**Issue by Diversus23** [Polyplastic/1c-parsing-tech-log#45]
В Git есть классный механизм [добавления релизов](https://github.com/Polyplastic/1c-parsing-tech-log/releases).
Есть просьба к Вам: добавьте пожалуйста все обработки с плагинами и сам cf-файл в релизы.
Не нужны будут сборка/пересборка обработок в epf + не у всех стоит EDT.
Было бы очень здорово для привлечения большего числа пользователей, да и удобно это, сразу зайти и скачать готовую обработку/cf-файл.
Спасибо!

**Comment by ivanov660** [comment]
Спасибо за интересное предложение. Подумаем над возможной реализацией. (это мы обязательно сделаем, но по возможности, т.к. в приоритетах пока стоят другие задачи)
Однако, я подхожу довольно скептически что данное изменение привлечет большое число пользователей.

**Comment by Diversus23** [comment]
Спасибо за ответ. Тут речь о том, что пользователям (во всяком случае мне), проще взять все обработки с cf-файлом и развернуть.
В принципе можно написать скрипт сборки релиза (файл-архив где все будет, включая инструкцию, обработки и cf).
Пруфы:
[Github Releases: публикация релизов](https://habr.com/ru/post/185444/)
[Release Your Software](https://github.blog/2013-07-02-release-your-software/)

**Comment by antoshik86** [comment]
Поддержу релиз бы хотелось бы. Если были бы Стартмани на инфостарте.  Но пока увы..

**Comment by antoshik86** [comment]
> привлечет большое число пользователей.

можно через телеграмм каналы пробовать популяризировать.

**Comment by ivanov660** [comment]
Функционал добавлен https://github.com/Polyplastic/1c-parsing-tech-log/releases/tag/v2.0.7.1
