### ISSUE TITLE
Некорректный разбор многострочных свойств

### ISSUE THREAD

**Issue by sfppk** [Polyplastic/1c-parsing-tech-log#7]
**Describe the bug**
В некоторых случаях свойства события "попадают" не по назначению

**To Reproduce**
Обнаружено при загрузке журнала с ошибками, свойство Context записывается не всегда корректно - иногда в Descr. Это затрудняет поиск.

**Expected behavior**
Нужно повысить стабильность разбора свойств. Проверить работу с квотированными строками, содержащими разделитель в тексте.

**Comment by ivanov660** [comment]
пример ошибки разбора
![image](https://user-images.githubusercontent.com/24763549/76495890-d90aad80-6448-11ea-9e3a-2b99122beba6.png)
