### ISSUE TITLE
Помогите разобраться

### ISSUE THREAD

**Issue by eliascav** [Polyplastic/1c-parsing-tech-log#79]
Есть замеры есть события старая версия обработки показывает данные новая нет. Что я делаю не так.
![image](https://user-images.githubusercontent.com/35498249/205734464-13ba788d-c956-4084-8273-7c52d7b9f361.png)
![image](https://user-images.githubusercontent.com/35498249/205734614-b827e64b-490a-4761-adb7-e6835604ea50.png)

**Comment by TestingTool-3** [comment]
Вы должны указать правильно все параметры в табличной части - замер, свойство (проверьте на дубли), тип события (если он указан), ключ (если указан) - их можно посмотреть в карточке элемента данных справочника события замера. Проверьте этот момент.
Еще должен конечно соответствовать интервал.
