### ISSUE TITLE
Помогите с первоначальной настройкой.

### ISSUE THREAD

**Issue by kaplunaleks** [Polyplastic/1c-parsing-tech-log#80]
Посмотрел статьи и видео которое было в WiKi и попытался поставить у себя.
Создал файл для тех журнала и 1С начала создавать файлы.
![image](https://github.com/Polyplastic/1c-parsing-tech-log/assets/17850298/9742b73f-e4c5-4b67-b5c1-83ed1238e7d0)
![image](https://github.com/Polyplastic/1c-parsing-tech-log/assets/17850298/6e61402a-1307-4d20-952c-15759f701bbf)

Добавил замеры указав места хранения файлов
![image](https://github.com/Polyplastic/1c-parsing-tech-log/assets/17850298/008eba71-2a9a-4dac-a586-4272abd67adf)
![image](https://github.com/Polyplastic/1c-parsing-tech-log/assets/17850298/4786eca0-32cc-4a5c-89d6-405589db4c34)

Но ошибки в событиях не появляются
![image](https://github.com/Polyplastic/1c-parsing-tech-log/assets/17850298/57865765-efd6-4aee-9761-d8f086b73ffc)

Помогите с настройкой, очень нужно понимать что происходит с базой.

**Comment by ivanov660** [comment]
Вопрос по настройке переадресовали коллеге. Обсуждение ушло в приват. Закрываем.
