### ISSUE TITLE
При загрузке внешней обработки (плагина) сообщение - использование синхронных методов на клиенте запрещено

### ISSUE THREAD

**Issue by yuriybylinkin** [Polyplastic/1c-parsing-tech-log#90]
Конфигурация установлена из раздела Релизы отсюда.
При загрузке внешней обработки (плагина) сообщение - использование синхронных методов на клиенте запрещено
![2024-01-06_16-24-21](https://github.com/Polyplastic/1c-parsing-tech-log/assets/1064356/fb396abd-fd74-4fc1-9dc8-a42947316d23)

**Comment by ivanov660** [comment]
В настройках конфигурации стоит вывод предупреждения об использовании синхронных методов и модальности. Поэтому данное сообщение будет выводиться, если обработки или отчеты не адаптированы под асинхронный режим.
Часть плагинов была адаптирована, часть еще нет. Если это вам доставляет дискомфорт, то в настройках конфигурации переключите в режим использовать. В этом случае предупреждений не будет.
