### ISSUE TITLE
Метод объекта не обнаружен (ЭтоLinuxСервер) в плагине МониторRAS

### ISSUE THREAD

**Issue by yuriybylinkin** [Polyplastic/1c-parsing-tech-log#91]
Наблюдается некая несогласованность в последнем релизе. Скачал конфигурацию и набор плагинов из последнего релиза (v2.0.9.11-2023.09.18).
При попытке воспользоваться плагином МониторRAS наблюдаю следующую ошибку:
![image](https://github.com/Polyplastic/1c-parsing-tech-log/assets/1064356/69a184f0-49e5-423f-a041-8d335796de15)

**Comment by ivanov660** [comment]
Посмотрим. Проблемная процедура должна присутствовать в релизе, если проблема подтвердится поправим. 
Чуть позже напишем.

**Comment by yuriybylinkin** [comment]
Сейчас в исходниках она есть, просто файл в релизах с конфигурацией собран 19 сентября, а плагины - 29 сентября

**Comment by ivanov660** [comment]
Пересобрали и выложили. Ошибка должна уйти.
